# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: ajax_app_test

production:
  adapter: postgresql
  encoding: unicode
  database: sakamotokouhei
  pool: 5
  username: postgres
  password: [R9zC5q3wg4msEaZx2nlzDCjuHIoNPJHf]
  host: localhost
